// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Generic class that matches all possible events from the native DownloadCallback interface.
sealed class DownloadCallbackEvent {
}

class OnDownloadProgressChangedEvent extends DownloadCallbackEvent {
  OnDownloadProgressChangedEvent({
    required this.current,
    required this.total,
    required this.timestamp,
    required this.remoteId,
    required this.path,
  });

  int current;

  int total;

  int timestamp;

  String remoteId;

  String path;

  List<Object?> _toList() {
    return <Object?>[
      current,
      total,
      timestamp,
      remoteId,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnDownloadProgressChangedEvent decode(Object result) {
    result as List<Object?>;
    return OnDownloadProgressChangedEvent(
      current: result[0]! as int,
      total: result[1]! as int,
      timestamp: result[2]! as int,
      remoteId: result[3]! as String,
      path: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnDownloadProgressChangedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(current, other.current) && _deepEquals(total, other.total) && _deepEquals(timestamp, other.timestamp) && _deepEquals(remoteId, other.remoteId) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnDownloadProgressChangedEvent(current: $current, total: $total, timestamp: $timestamp, remoteId: $remoteId, path: $path)';
  }
}

class OnDownloadFailedEvent extends DownloadCallbackEvent {
  OnDownloadFailedEvent({
    this.cause,
    required this.remoteId,
    required this.path,
  });

  String? cause;

  String remoteId;

  String path;

  List<Object?> _toList() {
    return <Object?>[
      cause,
      remoteId,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnDownloadFailedEvent decode(Object result) {
    result as List<Object?>;
    return OnDownloadFailedEvent(
      cause: result[0] as String?,
      remoteId: result[1]! as String,
      path: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnDownloadFailedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cause, other.cause) && _deepEquals(remoteId, other.remoteId) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnDownloadFailedEvent(cause: $cause, remoteId: $remoteId, path: $path)';
  }
}

class OnDownloadCancelledEvent extends DownloadCallbackEvent {
  OnDownloadCancelledEvent({
    required this.remoteId,
    required this.path,
  });

  String remoteId;

  /// Needed to track the event source coming through a single stream.
  String path;

  List<Object?> _toList() {
    return <Object?>[
      remoteId,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnDownloadCancelledEvent decode(Object result) {
    result as List<Object?>;
    return OnDownloadCancelledEvent(
      remoteId: result[0]! as String,
      path: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnDownloadCancelledEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(remoteId, other.remoteId) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnDownloadCancelledEvent(remoteId: $remoteId, path: $path)';
  }
}

class OnDownloadCompletedEvent extends DownloadCallbackEvent {
  OnDownloadCompletedEvent({
    required this.remoteId,
    required this.path,
    required this.bytes,
  });

  String remoteId;

  /// Needed to track the event source coming through a single stream.
  String path;

  /// The raw bytes of the file.
  Uint8List bytes;

  List<Object?> _toList() {
    return <Object?>[
      remoteId,
      path,
      bytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnDownloadCompletedEvent decode(Object result) {
    result as List<Object?>;
    return OnDownloadCompletedEvent(
      remoteId: result[0]! as String,
      path: result[1]! as String,
      bytes: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnDownloadCompletedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(remoteId, other.remoteId) && _deepEquals(path, other.path) && _deepEquals(bytes, other.bytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnDownloadCompletedEvent(remoteId: $remoteId, path: $path, bytes: $bytes)';
  }
}

class ConnectionStateEvent {
  ConnectionStateEvent({
    required this.remoteId,
    required this.connected,
  });

  String remoteId;

  bool connected;

  List<Object?> _toList() {
    return <Object?>[
      remoteId,
      connected,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectionStateEvent decode(Object result) {
    result as List<Object?>;
    return ConnectionStateEvent(
      remoteId: result[0]! as String,
      connected: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(remoteId, other.remoteId) && _deepEquals(connected, other.connected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConnectionStateEvent(remoteId: $remoteId, connected: $connected)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OnDownloadProgressChangedEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is OnDownloadFailedEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is OnDownloadCancelledEvent) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is OnDownloadCompletedEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectionStateEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return OnDownloadProgressChangedEvent.decode(readValue(buffer)!);
      case 130:
        return OnDownloadFailedEvent.decode(readValue(buffer)!);
      case 131:
        return OnDownloadCancelledEvent.decode(readValue(buffer)!);
      case 132:
        return OnDownloadCompletedEvent.decode(readValue(buffer)!);
      case 133:
        return ConnectionStateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Returns a broadcast [Stream] of events from the `getFileDownloadEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<DownloadCallbackEvent> getFileDownloadEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel getFileDownloadEventsChannel =
      EventChannel('dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getFileDownloadEvents$instanceName', pigeonMethodCodec);
  return getFileDownloadEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as DownloadCallbackEvent;
  });
}
    
/// Returns a broadcast [Stream] of events from the `getConnectionStateEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<ConnectionStateEvent> getConnectionStateEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel getConnectionStateEventsChannel =
      EventChannel('dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getConnectionStateEvents$instanceName', pigeonMethodCodec);
  return getConnectionStateEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as ConnectionStateEvent;
  });
}
    

class CustomGroupManagerApi {
  /// Constructor for [CustomGroupManagerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CustomGroupManagerApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Configures the SMP transport decorator for a specific device.
  ///
  /// [suffix] bytes are appended to every outgoing SMP packet.
  /// [opOverride] overrides byte 0 (op) of the SMP header.
  /// [flagsOverride] overrides byte 1 (flags) of the SMP header.
  /// All parameters are optional; omit to leave the field unmodified.
  Future<void> setupDecorator(String remoteId, Uint8List? suffix, int? opOverride, int? flagsOverride) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.setupDecorator$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId, suffix, opOverride, flagsOverride]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sends a custom SMP command and returns the raw response payload
  /// (the 8-byte SMP header is stripped before returning).
  ///
  /// [groupId]   – SMP group ID (e.g. `0x41` for a vendor-specific group).
  /// [commandId] – command within the group.
  /// [op]        – SMP operation code (`0` = read, `2` = write).
  /// [payload]   – string-keyed map CBOR-encoded as the request payload.
  Future<Uint8List> sendCustomCommand(String remoteId, int groupId, int commandId, int op, Map<String?, Object?> payload) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.sendCustomCommand$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId, groupId, commandId, op, payload]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Releases all native resources for the given device.
  Future<void> kill(String remoteId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.kill$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class FsManagerApi {
  /// Constructor for [FsManagerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FsManagerApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Starts the download of a single file with a specific device.
  /// Additional calls to a device that has an ongoing download causes a [PlatformException]
  /// to be thrown.
  Future<void> download(String remoteId, String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.download$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId, path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Pause an ongoing download
  Future<void> pauseTransfer(String remoteId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.pauseTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Resume an ongoing download
  Future<void> continueTransfer(String remoteId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.continueTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cancel an ongoing download
  Future<void> cancelTransfer(String remoteId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.cancelTransfer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> status(String remoteId, String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId, path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Kill the FsManager instance on the native platform.
  Future<void> kill(String remoteId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.kill$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remoteId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
