// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package no.nordicsemi.android.mcumgr_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Generic class that matches all possible events from the native DownloadCallback interface.
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class DownloadCallbackEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class OnDownloadProgressChangedEvent (
  val current: Long,
  val total: Long,
  val timestamp: Long,
  val remoteId: String,
  val path: String
) : DownloadCallbackEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnDownloadProgressChangedEvent {
      val current = pigeonVar_list[0] as Long
      val total = pigeonVar_list[1] as Long
      val timestamp = pigeonVar_list[2] as Long
      val remoteId = pigeonVar_list[3] as String
      val path = pigeonVar_list[4] as String
      return OnDownloadProgressChangedEvent(current, total, timestamp, remoteId, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      current,
      total,
      timestamp,
      remoteId,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnDownloadProgressChangedEvent
    return MessagesPigeonUtils.deepEquals(this.current, other.current) && MessagesPigeonUtils.deepEquals(this.total, other.total) && MessagesPigeonUtils.deepEquals(this.timestamp, other.timestamp) && MessagesPigeonUtils.deepEquals(this.remoteId, other.remoteId) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.current)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.total)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timestamp)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "OnDownloadProgressChangedEvent(current=$current, total=$total, timestamp=$timestamp, remoteId=$remoteId, path=$path)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OnDownloadFailedEvent (
  val cause: String? = null,
  val remoteId: String,
  val path: String
) : DownloadCallbackEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnDownloadFailedEvent {
      val cause = pigeonVar_list[0] as String?
      val remoteId = pigeonVar_list[1] as String
      val path = pigeonVar_list[2] as String
      return OnDownloadFailedEvent(cause, remoteId, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cause,
      remoteId,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnDownloadFailedEvent
    return MessagesPigeonUtils.deepEquals(this.cause, other.cause) && MessagesPigeonUtils.deepEquals(this.remoteId, other.remoteId) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cause)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "OnDownloadFailedEvent(cause=$cause, remoteId=$remoteId, path=$path)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OnDownloadCancelledEvent (
  val remoteId: String,
  /** Needed to track the event source coming through a single stream. */
  val path: String
) : DownloadCallbackEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnDownloadCancelledEvent {
      val remoteId = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      return OnDownloadCancelledEvent(remoteId, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      remoteId,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnDownloadCancelledEvent
    return MessagesPigeonUtils.deepEquals(this.remoteId, other.remoteId) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "OnDownloadCancelledEvent(remoteId=$remoteId, path=$path)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OnDownloadCompletedEvent (
  val remoteId: String,
  /** Needed to track the event source coming through a single stream. */
  val path: String,
  /** The raw bytes of the file. */
  val bytes: ByteArray
) : DownloadCallbackEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnDownloadCompletedEvent {
      val remoteId = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      val bytes = pigeonVar_list[2] as ByteArray
      return OnDownloadCompletedEvent(remoteId, path, bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      remoteId,
      path,
      bytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnDownloadCompletedEvent
    return MessagesPigeonUtils.deepEquals(this.remoteId, other.remoteId) && MessagesPigeonUtils.deepEquals(this.path, other.path) && MessagesPigeonUtils.deepEquals(this.bytes, other.bytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytes)
    return result
  }
  override fun toString(): String {
    return "OnDownloadCompletedEvent(remoteId=$remoteId, path=$path, bytes=${bytes.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionStateEvent (
  val remoteId: String,
  val connected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionStateEvent {
      val remoteId = pigeonVar_list[0] as String
      val connected = pigeonVar_list[1] as Boolean
      return ConnectionStateEvent(remoteId, connected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      remoteId,
      connected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionStateEvent
    return MessagesPigeonUtils.deepEquals(this.remoteId, other.remoteId) && MessagesPigeonUtils.deepEquals(this.connected, other.connected)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connected)
    return result
  }
  override fun toString(): String {
    return "ConnectionStateEvent(remoteId=$remoteId, connected=$connected)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnDownloadProgressChangedEvent.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnDownloadFailedEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnDownloadCancelledEvent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnDownloadCompletedEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionStateEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OnDownloadProgressChangedEvent -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is OnDownloadFailedEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OnDownloadCancelledEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OnDownloadCompletedEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ConnectionStateEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())



private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class GetFileDownloadEventsStreamHandler : MessagesPigeonEventChannelWrapper<DownloadCallbackEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GetFileDownloadEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getFileDownloadEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<DownloadCallbackEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<DownloadCallbackEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class GetConnectionStateEventsStreamHandler : MessagesPigeonEventChannelWrapper<ConnectionStateEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GetConnectionStateEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getConnectionStateEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<ConnectionStateEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ConnectionStateEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CustomGroupManagerApi {
  /**
   * Configures the SMP transport decorator for a specific device.
   *
   * [suffix] bytes are appended to every outgoing SMP packet.
   * [opOverride] overrides byte 0 (op) of the SMP header.
   * [flagsOverride] overrides byte 1 (flags) of the SMP header.
   * All parameters are optional; omit to leave the field unmodified.
   */
  fun setupDecorator(remoteId: String, suffix: ByteArray?, opOverride: Long?, flagsOverride: Long?)
  /**
   * Sends a custom SMP command and returns the raw response payload
   * (the 8-byte SMP header is stripped before returning).
   *
   * [groupId]   – SMP group ID (e.g. `0x41` for a vendor-specific group).
   * [commandId] – command within the group.
   * [op]        – SMP operation code (`0` = read, `2` = write).
   * [payload]   – string-keyed map CBOR-encoded as the request payload.
   */
  suspend fun sendCustomCommand(remoteId: String, groupId: Long, commandId: Long, op: Long, payload: Map<String?, Any?>): ByteArray
  /** Releases all native resources for the given device. */
  fun kill(remoteId: String)

  companion object {
    /** The codec used by CustomGroupManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CustomGroupManagerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CustomGroupManagerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.setupDecorator$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val suffixArg = args[1] as ByteArray?
            val opOverrideArg = args[2] as Long?
            val flagsOverrideArg = args[3] as Long?
            val wrapped: List<Any?> = try {
              api.setupDecorator(remoteIdArg, suffixArg, opOverrideArg, flagsOverrideArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.sendCustomCommand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val groupIdArg = args[1] as Long
            val commandIdArg = args[2] as Long
            val opArg = args[3] as Long
            val payloadArg = args[4] as Map<String?, Any?>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendCustomCommand(remoteIdArg, groupIdArg, commandIdArg, opArg, payloadArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.kill$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.kill(remoteIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FsManagerApi {
  /**
   * Starts the download of a single file with a specific device.
   * Additional calls to a device that has an ongoing download causes a [PlatformException]
   * to be thrown.
   */
  fun download(remoteId: String, path: String)
  /** Pause an ongoing download */
  fun pauseTransfer(remoteId: String)
  /** Resume an ongoing download */
  fun continueTransfer(remoteId: String)
  /** Cancel an ongoing download */
  fun cancelTransfer(remoteId: String)
  suspend fun status(remoteId: String, path: String): Long
  /** Kill the FsManager instance on the native platform. */
  fun kill(remoteId: String)

  companion object {
    /** The codec used by FsManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `FsManagerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FsManagerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.download$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val pathArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.download(remoteIdArg, pathArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.pauseTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.pauseTransfer(remoteIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.continueTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.continueTransfer(remoteIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.cancelTransfer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelTransfer(remoteIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val pathArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.status(remoteIdArg, pathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.kill$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.kill(remoteIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
