// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generic class that matches all possible events from the native DownloadCallback interface.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol DownloadCallbackEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct OnDownloadProgressChangedEvent: DownloadCallbackEvent {
  var current: Int64
  var total: Int64
  var timestamp: Int64
  var remoteId: String
  var path: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnDownloadProgressChangedEvent? {
    let current = pigeonVar_list[0] as! Int64
    let total = pigeonVar_list[1] as! Int64
    let timestamp = pigeonVar_list[2] as! Int64
    let remoteId = pigeonVar_list[3] as! String
    let path = pigeonVar_list[4] as! String

    return OnDownloadProgressChangedEvent(
      current: current,
      total: total,
      timestamp: timestamp,
      remoteId: remoteId,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      current,
      total,
      timestamp,
      remoteId,
      path,
    ]
  }
  static func == (lhs: OnDownloadProgressChangedEvent, rhs: OnDownloadProgressChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.current, rhs.current) && MessagesPigeonInternal.deepEquals(lhs.total, rhs.total) && MessagesPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp) && MessagesPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnDownloadProgressChangedEvent")
    MessagesPigeonInternal.deepHash(value: current, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: total, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "OnDownloadProgressChangedEvent(current: \(String(describing: current)), total: \(String(describing: total)), timestamp: \(String(describing: timestamp)), remoteId: \(String(describing: remoteId)), path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnDownloadFailedEvent: DownloadCallbackEvent {
  var cause: String? = nil
  var remoteId: String
  var path: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnDownloadFailedEvent? {
    let cause: String? = nilOrValue(pigeonVar_list[0])
    let remoteId = pigeonVar_list[1] as! String
    let path = pigeonVar_list[2] as! String

    return OnDownloadFailedEvent(
      cause: cause,
      remoteId: remoteId,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      cause,
      remoteId,
      path,
    ]
  }
  static func == (lhs: OnDownloadFailedEvent, rhs: OnDownloadFailedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.cause, rhs.cause) && MessagesPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnDownloadFailedEvent")
    MessagesPigeonInternal.deepHash(value: cause, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "OnDownloadFailedEvent(cause: \(String(describing: cause)), remoteId: \(String(describing: remoteId)), path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnDownloadCancelledEvent: DownloadCallbackEvent {
  var remoteId: String
  /// Needed to track the event source coming through a single stream.
  var path: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnDownloadCancelledEvent? {
    let remoteId = pigeonVar_list[0] as! String
    let path = pigeonVar_list[1] as! String

    return OnDownloadCancelledEvent(
      remoteId: remoteId,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      remoteId,
      path,
    ]
  }
  static func == (lhs: OnDownloadCancelledEvent, rhs: OnDownloadCancelledEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnDownloadCancelledEvent")
    MessagesPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "OnDownloadCancelledEvent(remoteId: \(String(describing: remoteId)), path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnDownloadCompletedEvent: DownloadCallbackEvent {
  var remoteId: String
  /// Needed to track the event source coming through a single stream.
  var path: String
  /// The raw bytes of the file.
  var bytes: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnDownloadCompletedEvent? {
    let remoteId = pigeonVar_list[0] as! String
    let path = pigeonVar_list[1] as! String
    let bytes = pigeonVar_list[2] as! FlutterStandardTypedData

    return OnDownloadCompletedEvent(
      remoteId: remoteId,
      path: path,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      remoteId,
      path,
      bytes,
    ]
  }
  static func == (lhs: OnDownloadCompletedEvent, rhs: OnDownloadCompletedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnDownloadCompletedEvent")
    MessagesPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
  }

  public var description: String {
    return "OnDownloadCompletedEvent(remoteId: \(String(describing: remoteId)), path: \(String(describing: path)), bytes: \(String(describing: bytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionStateEvent: Hashable, CustomStringConvertible {
  var remoteId: String
  var connected: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionStateEvent? {
    let remoteId = pigeonVar_list[0] as! String
    let connected = pigeonVar_list[1] as! Bool

    return ConnectionStateEvent(
      remoteId: remoteId,
      connected: connected
    )
  }
  func toList() -> [Any?] {
    return [
      remoteId,
      connected,
    ]
  }
  static func == (lhs: ConnectionStateEvent, rhs: ConnectionStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && MessagesPigeonInternal.deepEquals(lhs.connected, rhs.connected)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionStateEvent")
    MessagesPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connected, hasher: &hasher)
  }

  public var description: String {
    return "ConnectionStateEvent(remoteId: \(String(describing: remoteId)), connected: \(String(describing: connected)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return OnDownloadProgressChangedEvent.fromList(self.readValue() as! [Any?])
    case 130:
      return OnDownloadFailedEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return OnDownloadCancelledEvent.fromList(self.readValue() as! [Any?])
    case 132:
      return OnDownloadCompletedEvent.fromList(self.readValue() as! [Any?])
    case 133:
      return ConnectionStateEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OnDownloadProgressChangedEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? OnDownloadFailedEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? OnDownloadCancelledEvent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OnDownloadCompletedEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionStateEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());



private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class GetFileDownloadEventsStreamHandler: PigeonEventChannelWrapper<DownloadCallbackEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: GetFileDownloadEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getFileDownloadEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<DownloadCallbackEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class GetConnectionStateEventsStreamHandler: PigeonEventChannelWrapper<ConnectionStateEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: GetConnectionStateEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.mcumgr_flutter.McumgrFlutterEvents.getConnectionStateEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<ConnectionStateEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CustomGroupManagerApi {
  /// Configures the SMP transport decorator for a specific device.
  ///
  /// [suffix] bytes are appended to every outgoing SMP packet.
  /// [opOverride] overrides byte 0 (op) of the SMP header.
  /// [flagsOverride] overrides byte 1 (flags) of the SMP header.
  /// All parameters are optional; omit to leave the field unmodified.
  func setupDecorator(remoteId: String, suffix: FlutterStandardTypedData?, opOverride: Int64?, flagsOverride: Int64?) throws
  /// Sends a custom SMP command and returns the raw response payload
  /// (the 8-byte SMP header is stripped before returning).
  ///
  /// [groupId]   – SMP group ID (e.g. `0x41` for a vendor-specific group).
  /// [commandId] – command within the group.
  /// [op]        – SMP operation code (`0` = read, `2` = write).
  /// [payload]   – string-keyed map CBOR-encoded as the request payload.
  func sendCustomCommand(remoteId: String, groupId: Int64, commandId: Int64, op: Int64, payload: [String?: Any?]) async throws -> FlutterStandardTypedData
  /// Releases all native resources for the given device.
  func kill(remoteId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CustomGroupManagerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CustomGroupManagerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CustomGroupManagerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Configures the SMP transport decorator for a specific device.
    ///
    /// [suffix] bytes are appended to every outgoing SMP packet.
    /// [opOverride] overrides byte 0 (op) of the SMP header.
    /// [flagsOverride] overrides byte 1 (flags) of the SMP header.
    /// All parameters are optional; omit to leave the field unmodified.
    let setupDecoratorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.setupDecorator\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupDecoratorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        let suffixArg: FlutterStandardTypedData? = nilOrValue(args[1])
        let opOverrideArg: Int64? = nilOrValue(args[2])
        let flagsOverrideArg: Int64? = nilOrValue(args[3])
        do {
          try api.setupDecorator(remoteId: remoteIdArg, suffix: suffixArg, opOverride: opOverrideArg, flagsOverride: flagsOverrideArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupDecoratorChannel.setMessageHandler(nil)
    }
    /// Sends a custom SMP command and returns the raw response payload
    /// (the 8-byte SMP header is stripped before returning).
    ///
    /// [groupId]   – SMP group ID (e.g. `0x41` for a vendor-specific group).
    /// [commandId] – command within the group.
    /// [op]        – SMP operation code (`0` = read, `2` = write).
    /// [payload]   – string-keyed map CBOR-encoded as the request payload.
    let sendCustomCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.sendCustomCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendCustomCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        let groupIdArg = args[1] as! Int64
        let commandIdArg = args[2] as! Int64
        let opArg = args[3] as! Int64
        let payloadArg = args[4] as! [String?: Any?]
        Task { @MainActor in
          do {
            let result = try await api.sendCustomCommand(remoteId: remoteIdArg, groupId: groupIdArg, commandId: commandIdArg, op: opArg, payload: payloadArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendCustomCommandChannel.setMessageHandler(nil)
    }
    /// Releases all native resources for the given device.
    let killChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.CustomGroupManagerApi.kill\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      killChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        do {
          try api.kill(remoteId: remoteIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      killChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FsManagerApi {
  /// Starts the download of a single file with a specific device.
  /// Additional calls to a device that has an ongoing download causes a [PlatformException]
  /// to be thrown.
  func download(remoteId: String, path: String) throws
  /// Pause an ongoing download
  func pauseTransfer(remoteId: String) throws
  /// Resume an ongoing download
  func continueTransfer(remoteId: String) throws
  /// Cancel an ongoing download
  func cancelTransfer(remoteId: String) throws
  func status(remoteId: String, path: String) async throws -> Int64
  /// Kill the FsManager instance on the native platform.
  func kill(remoteId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FsManagerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FsManagerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FsManagerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts the download of a single file with a specific device.
    /// Additional calls to a device that has an ongoing download causes a [PlatformException]
    /// to be thrown.
    let downloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.download\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        let pathArg = args[1] as! String
        do {
          try api.download(remoteId: remoteIdArg, path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      downloadChannel.setMessageHandler(nil)
    }
    /// Pause an ongoing download
    let pauseTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.pauseTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        do {
          try api.pauseTransfer(remoteId: remoteIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseTransferChannel.setMessageHandler(nil)
    }
    /// Resume an ongoing download
    let continueTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.continueTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      continueTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        do {
          try api.continueTransfer(remoteId: remoteIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      continueTransferChannel.setMessageHandler(nil)
    }
    /// Cancel an ongoing download
    let cancelTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.cancelTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        do {
          try api.cancelTransfer(remoteId: remoteIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelTransferChannel.setMessageHandler(nil)
    }
    let statusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.status\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      statusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        let pathArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.status(remoteId: remoteIdArg, path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      statusChannel.setMessageHandler(nil)
    }
    /// Kill the FsManager instance on the native platform.
    let killChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mcumgr_flutter.FsManagerApi.kill\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      killChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let remoteIdArg = args[0] as! String
        do {
          try api.kill(remoteId: remoteIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      killChannel.setMessageHandler(nil)
    }
  }
}
